### ISSUE TITLE
Feature Request: show player names at the crosshair

### ISSUE THREAD

**Issue by crscum** [skullernet/q2pro#121]
I'd really like a variable to set something like cl_draw_playername. Seeing the name of your opponent when targetting him would be more fun, in my opinion.

I managed to integrate that feature in AprQ2 and r1q2 and some other quake versions (quake1), but I am unable to do the same in q2pro.

I am not really a coder, but basically, I just copied/pasted the corresponding stuff found in the quake2 client QuDos and succeeded in making it work in those quake versions.

Since there appear to be considerable differences in function definitions etc. in q2pro, I failed to get that code into this client.

So if someone else were willing to do that (and I think that it would not be a huge task for a real coder unlike myself), this would be much appreciated.

**Comment by sthalik** [comment]
Can you even implement that? The netcode provides limited information about entities.

Also use a mod like Tourney for all multiplayer, rather than the default `baseq<<PLATFORM>>.<<SOEXT>>`.

You can see the https://github.com/skullernet/opentdm repository that's open-source and ABI-compatible with this Quake 2 distribution. Use this. Many mods come with the `id` command.

**Comment by skullernet** [comment]
Although doable, this feature doesn't belong to Q2 client. Rejected. As sthalik said, some mods support player identification, you can use that.
