### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by messiahh** [skullernet/q2pro#158]
How compile for mac ???

**Comment by Mathyn** [comment]
I just follow the standard compile steps. For me it was as easy as doing `make` in the root of the project.

**Comment by skullernet** [comment]
macOS is unsupported as it is impossible for me to do development and QC on. However, it is a POSIX compatible OS, has package managers and an SDL2 port, so just following general building instructions might work for you.

**Comment by darkshade9** [comment]
I've been fortunate to have access to a relatively recent Mac for testing, these steps work with Meson and Mac Intel builds, I have not tested Apple Silicon but I imagine an adjustment to the `PKG_CONFIG_PATH` because brew installs libs to a different directory should do the trick.

https://github.com/actionquake/q2pro/blob/master/.github/workflows/build.yml#L154-L186

**Comment by kke** [comment]
Not sure if the `meson.build` change is needed, the `qal.h` changes is what made it work finally.

**Comment by kke** [comment]
And to make OpenAL audio work:

```diff
diff --git a/src/client/sound/qal.c b/src/client/sound/qal.c
index ebe610ce..97585e02 100644
--- a/src/client/sound/qal.c
+++ b/src/client/sound/qal.c
@@ -142,6 +142,8 @@ void QAL_Shutdown(void)
 static const char *const al_drivers[] = {
 #ifdef _WIN32
     "soft_oal", "openal32"
+#elif defined(__APPLE__)
+  "libopenal.1.dylib", "libopenal.dylib"
 #else
     "libopenal.so.1", "libopenal.so"
 #endif
```
