### ISSUE TITLE
[feature request] clientside weapon position on screen

### ISSUE THREAD

**Issue by MrBoozer** [skullernet/q2pro#165]
Would be nice to have cl_gun_x y z cvars that'd work on clients side.

**Comment by MrBoozer** [comment]
I think the opposite. Some positions look pretty cool

**Comment by voivodpl** [comment]
I use custom hardcoded **gun_** values in my mod(for now). Each weapon would need to have it's own value really... Check REdux mod. I think they look quite ok.
However you can find issue with cut off v_models :).

I say mod the game dll yourself and put it on your server. Not much work.

**Comment by zhprzq2** [comment]
> Why is this useful? Q2 gun models usually look bad unless they are in default position on the screen.

Wow that's strange indeed that such a skilled developer blinged up in logics has failed to reveal the cause and the effect. Gun models look so bad exactly because of the default positioning, that overlaps almost half of players fov...

**Comment by zhprzq2** [comment]
> Why is this useful? Q2 gun models usually look bad unless they are in default position on the screen.

Wow that's strange indeed that such a skilled developer blinged up in logics has failed to reveal the cause and the effect. Gun models look so bad exactly because of the default positioning, that overlaps almost half of players fov...
here are some screens for instance:
![rg1](https://user-images.githubusercontent.com/122355584/211527583-eeccfa22-b0c9-4a80-a57c-bc7ab5f3bc82.png)
![rg2](https://user-images.githubusercontent.com/122355584/211527597-92ade9c0-6d68-4ade-afd4-bf67167a90c3.png)

**Comment by zhprzq2** [comment]
спасибо, бро!
