### ISSUE TITLE
how to adjust gun fov?

### ISSUE THREAD

**Issue by xboxownzuall** [skullernet/q2pro#205]
What's the gun fov command? So i can adjust it correctly for multiplayer it's too zoomed in.No im not talking about the games fov, im talking about the guns fov too close to the screen.

**Comment by Kormann** [comment]
Type on console
 `cl_adjustfov "1"`

or insert in your q2config.cfg
 `set cl_adjustfov "1"`

I recommend also using `fov "90"` if you want the default quake 2 fov.

@skullernet need to change **cl_adjustfov "1"** to default because a lot of people dislike the zoomed gun and they keep asking about how to change it back to normal.

**Comment by eGax** [comment]
A better idea would be to add a separate gun fov cvar IMO.
