### ISSUE TITLE
"cl_http_proxy" broke server's browser in menu

### ISSUE THREAD

**Issue by vic7or777** [skullernet/q2pro#217]
set cl_http_proxy q2.playground.ru:27980
this make not working observe in menu q2servers.com
console write error:
[HTTP] Failed to fetch 'q2servers.com/?raw=2': 403 Forbidden

**Comment by jar3817** [comment]
`403 Forbidden`: you aren't allowed to use that server for a proxy. Since the browser fetches the data from q2servers.com via http, that makes perfect sense. The problem is with your proxy server, not q2pro.

**Comment by vic7or777** [comment]
this cvar should allow fast downloading of maps, textures, etc.
doc says: cl_http_proxy - HTTP proxy server to use for downloads. Default value is empty (direct connection).

this make fast downloading via http from specified server, but also affect menu browser
q2.playground.ru:27980 is not proxy, its file server, like ftp.

**Comment by jar3817** [comment]
Well, almost. 
A Proxy server is just a privileged path through a network. Q2Pro will automatically download file/maps/etc using http (the fast method) anyway, you only need to use a proxy server when your q2 client can't access the download server directly. It's not a way of specifying a particular server to download from, it just acts as the middle-man: you talk to the proxy, the proxy talks to the download server. The download server itself is set in the quake2 server config, so that isn't something you can change on the client side.

I would say 99% of players don't need a proxy server set, unless you're trying to play on the corporate network at work. If you're at home, you don't need it.

Your issue is that by setting the http proxy value, ALL http traffic goes through that proxy, including the browser data, etc. It looks like you set that value to a quake 2 server address rather than a valid http proxy address (typically port `80` or `8080`)

**Comment by vic7or777** [comment]
I think 99% of players need fast downloading.
If cl_http_proxy is not specified, maps downloads very slow.
q2.playground.ru:27980 is fast download http server configured by skuller (author of q2pro and admin of q2.playground.ru)

Now q2pro (with playground server) has two features: fast download via proxy, and server browser, but it's possible to use only one.

Because it's not logical to make q2 downloading proxy server works with any http traffic, 
i think better way to separate functions, for example:
cl_http_proxy_enable 1 - proxy only downloads (default)
cl_http_proxy_enable 2 - proxy only browser
cl_http_proxy_enable 3 - both

**Comment by jar3817** [comment]
I'm sorry, you don't seem to understand how any of this works.

Yes, everyone wants fast http downloads. This happens because of libcurl compiled into q2pro. This has nothing to do with `cl_http_proxy` at all.

**Comment by QwazyWabbitWOS** [comment]
The HTTP download server URL is specified by the _server_ in `sv_downloadserver`. This string is the URL the client receives from the game server for direct connection to the fast download server. 

The `cl_http_proxy` cvar is not a replacement for the `sv_downloadserver` string and cannot be used to force redirection in the way you are trying to use it.

Use `cl_http_default_url` in client configuration to specify the fast download server in cases where the game server doesn't specify `sv_downloadserver` for the client. `cl_http_default_url` is not documented in the client or server q2pro documents. 

Even so, specifying a fast download server requires close coordination of content between the game server and the HTTP server and should only be used when the game content and HTTP server are controlled by the same admin. Different mods require different content and the URLs must be carefully chosen per game server.

**Comment by skullernet** [comment]
As already explained, this bug report is invalid. `cl_http_proxy` is not meant to be used this way.

**Comment by vic7or777** [comment]
some years ago saw at quake2.com.ru recommendation to set cl_http_proxy q2.playground.ru:27980 (but now can't find it)
doc say: HTTP proxy server to use for **downloads**.
Ok, I will suppose the information above obsoleted.

**Comment by skullernet** [comment]
That information is not correct. The only way it could have worked is by chance. HTTP downloads should work automatically without any additional configuration on the client (*unless* you have a legitimate reason to use HTTP proxy, but that's entirely different matter).
