### ISSUE TITLE
Filelists

### ISSUE THREAD

**Issue by m4son** [skullernet/q2pro#220]
I am not sure if i understand it correctly, but shouldn't filelist specify what files players should have to play on server? 
I cant get filelist to download unless i push it manually with download some_file
Server is r1861

**Comment by skullernet** [comment]
Not downloading a filelist unconditionally is a feature to avoid unnecessary HTTP traffic. Client won't download a filelist unless it is missing files. Filelists are mostly there so that the client can download all mod data at once (possibly in form of packfiles) rather than downloading small portions of it. Also, they can help with broken maps/mods that don't precache data properly.
