### ISSUE TITLE
Ability to add more paths to the search path

### ISSUE THREAD

**Issue by ndit-dev** [skullernet/q2pro#246]
Would love the ability to add more paths to the search path either during build or through a cvar. 
Today `basedir` and `gamedir` (and `configdir`) exists, would like to be able to use an additional directory to the search path that overrides `gamedir` if files with same name exist in both gamedir and the additional dir.

In our use case we want have a separate folder, under root folder of q2pro, neighboring the gamedir, that we use for steams cloud synchronization functionality.

```
[q2pro root direcotry]
├── [CloudStore]
│   ├── steam_autocloud.vdf
│   ├── pak25.pkz
│   ├── pak26.pkz
│   ├── autoexec.cfg
│   └── ...
├── [action]
│   ├── gamearm.so
│   ├── gamex86_64.so
│   ├── autoexec.cfg
│   └── ...
├── aqtion
├── launch.sh
├── libsteam_api.dylib
├── q2pro
├── q2proded
└── steam_appid.txt
```

**Comment by ndit-dev** [comment]
also wonder if there is a particular reason that COM_CONFIG_CFG is named differently on Win and Linux, has it always been like that? It makes cross platform synchronization of settings a bit tricky.

**Comment by skullernet** [comment]
> would like to be able to use an additional directory to the search path that overrides gamedir if files with same name exist in both gamedir and the additional dir.

Overriding files in gamedir seems counter-intuitive from user perspective. User should be able to modify any file in gamedir and see the effect immediately. I think the functionality you describe can be useful, but in very specific use case. Thus this is not something that should be upstreamed IMO.

> Also wonder if there is a particular reason that COM_CONFIG_CFG is named differently on Win and Linux?

Q2PRO was made to use `q2config.cfg` on Windows to avoid clashes with other clients that use `config.cfg`, because config files written by Q2PRO are not interchangeable with other clients. On Linux Q2PRO was supposed to run in its own home directory so that this problem could be avoided. Indeed it is a bit messy, but changing this would break backward compatibility, which is a bit unfortunate.

**Comment by ndit-dev** [comment]
> Overriding files in gamedir seems counter-intuitive from user perspective. User should be able to modify any file in gamedir and see the effect immediately. I think the functionality you describe can be useful, but in very specific use case. Thus this is not something that should be upstreamed IMO.
Thank you for your feedback, agree with your reasoning.

`Q2PRO was made to use q2config.cfg on Windows to avoid clashes with other clients that use config.cfg, because config files written by Q2PRO are not interchangeable with other clients. On Linux Q2PRO was supposed to run in its own home directory so that this problem could be avoided. Indeed it is a bit messy, but changing this would break backward compatibility, which is a bit unfortunate.`
Thx for clarifying the background, agree it would be a mess to change it now even if it's inconsistent.
