### ISSUE TITLE
Layout Strings

### ISSUE THREAD

**Issue by q2modder** [skullernet/q2pro#250]
When printing basic text with layout strings there are three ways provided:

1. string - plain white text
2. string1 - plain white text
3. string2 - green text

in r1q2, string1 prints plain white text, but in q2pro nothing prints. I know its redundant, but it's just something I encountered.

**Comment by skullernet** [comment]
There is no such layout program keyword `string1` in original Quake 2. It just happens so that R1Q2 parses any keyword starting with `string` as regular string (except `string2` which is hard coded to display green text). Same with `cstring` by the way.

Is there any particular reason Q2PRO should support `string1`? It's not standard.

**Comment by q2modder** [comment]
You're right. I thought string1 was part of the of the original code, but It's not in there at all. I guess I just assumed if there was a string2 there would also be a string1. :)

**Comment by skullernet** [comment]
Closing then.
