### ISSUE TITLE
Support for stereo wav and other fileformats?

### ISSUE THREAD

**Issue by ndit-dev** [skullernet/q2pro#252]
Would it be a big hassle to add support for other sound files than mono .wav?
Stereo would be nice when playing music to players, as well as higher quality weapon and effect sounds.

Bonus for .ogg support ^^.

**Comment by skullernet** [comment]
Supporting stereo WAV files shouldn't be too hard in OpenAL case. In legacy software mixer case this will be harder. But for what purpose exactly? For sound effects that are positioned in 3D space stereo makes little sense. I think OpenAL disables 3D spatialization for non-mono sources altogether, but that can be changed with extensions.

OGG only makes sense for longer files that can't be fully buffered in memory and supporting that will require major changes since that would require dynamic streaming to OpenAL.

**Comment by ndit-dev** [comment]
For sounds that are positioned in 3D space stereo makes no sense. But for sound effects that are not positioned it could make the sound more immersive.

**A few examples where stereo would make the experience better.**
The players own weapons sounds for shooting, reloading, weapon handling etc
Music, menu sounds and other SFX sounds
Radio commands in Action Quake
etc
