### ISSUE TITLE
CFLAG discrepancy between meson and Makefile

### ISSUE THREAD

**Issue by darkshade9** [skullernet/q2pro#258]
I am not familiar with `meson` but I am noticing the CFLAGS that used to be passed during compile steps are not visible with increased compile log verbosity, example:

meson:
>```gcc -Iq2proded.p -I. -I.. -I../inc -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=gnu99 -O2 -g -DHAVE_CONFIG_H -D_GNU_SOURCE -Wpointer-arith -Wformat-security -DUSE_SERVER=1 -MD -MQ q2proded.p/src_server_commands.c.o -MF q2proded.p/src_server_commands.c.o.d -o q2proded.p/src_server_commands.c.o -c ../src/server/commands.c```

Makefile:
>```gcc -c -Werror -std=gnu99 -O2 -Wall -g -MMD  -iquote./inc -fvisibility=hidden -DCPUSTRING='"x86_64"' -DBUILDSTRING='"Linux"' -DREVISION=1 -DVERSION='"r1~2627c06"' -DBASEGAME='"baseq2"' -DDEFGAME='""' -DDATADIR='"."' -DLIBDIR='"."' -DHOMEDIR='""' -DUSE_SERVER=1 -DUSE_AC_SERVER=1 -DUSE_MVD_SERVER=1 -DUSE_MVD_CLIENT=1 -DUSE_ZLIB=1  -DUSE_ICMP=1 -DUSE_SYSCON=1 -DUSE_FPS=1 -DUSE_PACKETDUP=1 -DUSE_TESTS=1 -D_DEBUG -o .q2proded/src/server/commands.o src/server/commands.c```

Does `meson` suppress all of these extra flags that are set via `config.set10` and `config.set_quoted` or is it truly not building with these parameters?

**Comment by eli-schwartz** [comment]
> Does `meson` suppress all of these extra flags that are set via `config.set10` and `config.set_quoted` or is it truly not building with these parameters?

Meson uses:

https://github.com/skullernet/q2pro/blob/61b78cea014c5a6a6562092cd11ac9bbb2b9f150/inc/shared/shared.h#L26-L28

Since all the defines are set via a header config file (created in Meson via `config.set10()` followed by `configure_file()`), they aren't needed as -D defines too. Therefore the meson.build simply opts to not add them as e.g. `c_args: ` (per-target flags) or `add_project_arguments()` (project-wide flags).

**Comment by skullernet** [comment]
Most of `USE_` flags are passed through config.h in Meson case, like eli-schwartz described.
There is no issue here, thus closing.
