### ISSUE TITLE
Savegame on dedicated servers

### ISSUE THREAD

**Issue by ThePhatman** [skullernet/q2pro#267]
While porting [Maracoop](https://bitbucket.org/neozeed/q2dos/src/master/coop/) to Game API version 3 (from its Q2DOS Game API version 4 original), I noticed that Q2PRO in dedicated server mode did not seem to be calling `WriteLevel()`.

That's when I noticed [this code](https://github.com/skullernet/q2pro/blob/546e32f107250f5b8caae1c528d4af3610870e21/src/server/save.c#L435) in the server source which explicitly prevents a dedicated server from saving the game state. The Maracoop save games used when players go back and forth between two map/levels are based on the Yamagi save game format and I could readily set the `GMF_ENHANCED_SAVEGAMES` bit on the `g_features` cvar, but the fact that the server is dedicated will stop that in its tracks.

For the time being it runs perfectly with the [r1q2-tsmod](https://github.com/tastyspleen/r1q2-tsmod) `r1q2ded` executable and otherwise runs perfectly under `q2proded`. Please let me know your intent regarding this issue, I will deploy a workaround if you intend to keep this dedicated server exclusion in place and may do so for older versions of Q2PRO dedicated servers.

**Comment by skullernet** [comment]
Reason for this is that single player support (including savegames) has once been removed from Q2PRO entirely, and only patched back later. I didn't consider coop support at all at the time it was patched back, focusing only on single player, thus savegame code has been made listen server only. In fact, when building `q2proded` savegame code is omitted from executable completely.

I can probably remove `if (dedicated)` lines so that savegames will work with `q2pro` executable launched in dedicated mode. Always compiling in savegames code when building `q2proded` seems a bit too much though, considering how rarely coop is used. Maybe I'll make a compile time option for this.

**Comment by ThePhatman** [comment]
Sounds good. I will test is out shortly.

**Comment by ThePhatman** [comment]
This fix is confirmed.

StroggPharm.servequake.com:27910 now properly saves and loads map states when changing levels using q2proded r2230.
I will leave the server running q2proded instead of r1q2ded (tsmod) for general testing of this configuration.
