### ISSUE TITLE
Error reported in an infinite loop

### ISSUE THREAD

**Issue by ThePhatman** [skullernet/q2pro#269]
Hi skullernet,

I was doing some play testing on a map with over 900 monsters and when fighting a Widow I suddenly got this message (while discharging a BFG at the monster)

```add_msg_packet: Phatman: out of message slots```

The nature of the error is less concerning to me than the fact that the server became unresponsive because it kept dumping the error (including about 500,000 lines of it in my log file). Could you see about ensuring that either the client gets dropped or the server goes down in such cases? If you also want more info about what produced the circumstances, we could do that but I'd like to ensure that the server can recover -- disconnecting from the client side had no effect, the server continued dumping the error until I forcibly shut down the process.

Thank you!

**Comment by skullernet** [comment]
That's odd. What you describe should never happen. The message itself is not even an error, it's just a warning and should be intermittent/recoverable (unless overflow occurs on reliable message on which client is dropped). Perhaps the game itself entered some kind of infinite loop? There have been such bugs in the past.

More info is needed: how to reproduce this, or a backtrace leading to offending [line](https://github.com/skullernet/q2pro/blob/master/src/server/send.c#L486) when looping occurs.

**Comment by ThePhatman** [comment]
I was able to reproduce the issue and what I can tell you is that it [seems to occur during a `gi.bprintf` frag notification from the game library side](https://bitbucket.org/neozeed/q2dos/src/839f30a40ba5879ff0bd52fedcf30d5329943f8f/coop/g_combat.c#lines-401), which if true is definitely not being called in a looping context but is certainly a reliable message transmission request.

Further observations (for now) are that it seems that it is occurring consistently after a total of about 1,000 calls to `gi.bprintf`, having occurred during the same map level over a span of about 20 minutes or so (as stated, there are over 900 monsters on this map). I will gather more information about what is happening on the game library side when the looping message is occurring and get back to you.

**Comment by skullernet** [comment]
Size of client message pool is 1024, so if more than 1024 bprintf calls occur over short period of time before these messages are pushed to the client, it is expected that server will run out if message slots for this client. But it should just kick the client in this case, not sure why would there be an infinite loop.

On other hand, if all message slots are occupied, but the next message is unreliable, server *will* spam this warning on each unreliable message but will not kick the client. Maybe this is what you are seeing and server just appears to hang due to slow disk i/o. If this is what's happening maybe this warning should be demoted to debug message. Anyway, with over 900 monsters you are really pushing the engine limits here :)

**Comment by ThePhatman** [comment]
It turns out that the root cause of the issue had to do with the death movement frame sequence of monsters being frozen which was causing the looping to occur. 

I apologize for not realizing it sooner. It took quite a bit of time for me to trace it down given that it was only happening near the end of such a long map to play test in order to reproduce the issue.

Thank you.
