### ISSUE TITLE
have only 20fps on Linux

### ISSUE THREAD

**Issue by 12sunflowers** [skullernet/q2pro#277]
Hello! Its strange. 
I feel framerate is very slow. 
timerefresh show is 20fps only. Why? How to increase? My PC can do more fps in this game)
was tried cl_async 0\1 not help
echo $cl_async 17
echo $cl_fps 17
cl_maxfps 60
r_maxfps 0

PC old but can handle q2 and others retro games with high fps
c2d q6600, gf9800gtx(340.108), 4gb ram
Devuan Linux distro x64, X11, XFCE

PS in game console at after game launch i see yellow text glx_ext_swap_control not found

**Comment by 12sunflowers** [comment]
Yahoo! SOLVED!))
change vid_driver x11 to vid_driver sdl

**Comment by skullernet** [comment]
`vid_driver x11` should also work. Sounds like you get an indirect GLX context or software rendering. Probably has something to do with old NVIDIA driver version because it works fine with 470.141. I've added some additional logging to master branch, can you launch `q2pro +set vid_driver x11 +set developer 1 +set logfile 1 +strings` and upload resulting log somewhere, along with `glxinfo` command output?

**Comment by 12sunflowers** [comment]
q2pro log
https://pastebin.com/Lbp745ck

glxinfo
https://pastebin.com/TQjgaq5x

**Comment by skullernet** [comment]
Thanks.

> both x11 and sdl use hardware render

That's not true, in Q2PRO log it says `GL_RENDERER: llvmpipe (LLVM 15.0.5, 128 bits)`, which is software renderer. This explains low FPS.

I've looked at the differences between how SDL setups GLX and Q2PRO does it, looks like SDL doesn't even load `libGLX.so.0` and gets `glX*` function pointers from `libGL.so.1`. So I've changed it to link to `-lGL` instead of `-lGLX`. Can you rebuild with this change and test again?
