### ISSUE TITLE
[a suggestion] Visual Studio Project Release

### ISSUE THREAD

**Issue by q2modder** [skullernet/q2pro#279]
I'm a casual coder and I use Visual Studio 2022 for all my Quake 2 modding projects. I would like to do some modifications to the q2proded server code to complement my changes to the game library. I saw your instructions to compile with Meson/Ninja and I did get it to work, but now there is the issue of making it into a Visual Studio project. For us Windows developers it's a pretty difficult task to install and configure all the programs needed to compile your code. If I can make a suggestion, could you please release a Visual Studio Q2PRO Project? maybe just once a year around Christmas? :)

I have spoken with other coders in the community and they would be interested in this as well.

**Comment by skullernet** [comment]
You can try to generate Visual Studio solution with Meson. I think this Meson feature is experimental but it might work.

Supporting another build system is a no-go, sorry. Especially such awfully text editor unfriendly like Visual Studio XML files. I've tried maintaining Visual Studio solutions in the past, but it got bothersome very soon. And there's hardly any value in semi-maintained version which will be broken most of the time.

**Comment by QwazyWabbitWOS** [comment]
CMake would have been preferable.
This isn't current q2pro and it's a VS2019 solution, not 2022 but it's what I use to build and debug into the server code when debugging mods. It ought to upgrade to 2022 without too much difficulty. This solution is not intended to be used to build clients or end user programs.
https://github.com/QwazyWabbitWOS/q2pro

**Comment by skullernet** [comment]
CMake syntax is awful. Probably even worse than plain GNU makefile.

**Comment by QwazyWabbitWOS** [comment]
LOL. You'll get no argument from me on that. :)
But VS knows how to produce solution and projects from CMake, which makes life a bit easier for us VS-dedicated types.

**Comment by q2modder** [comment]
I was able to generate a Q2PRO Visual Studio project with Meson. It was surprisingly easy... I have provided the steps below if you want to update your instructions.

Visual Studio Project Creation:

1. Download and Install Meson.
2. Download and extract the Q2PRO source code to a folder. e.g. "c:\q2pro-r2444"
3. Run "x64 Native Tools Command Prompt" in Administrator Mode.
4. Change to the source code directory. e.g. "cd\q2pro-r2444"
5. Execute the following command: "meson setup c:\q2pro-vsproject --backend=vs

**Comment by QwazyWabbitWOS** [comment]
I would modify these instructions to clone the repository, rather than downloading and extracting a particular source archive.
This all works, with the advisory that the resulting project is x86 build only, not x64. Perhaps in the near future Microsoft will default to x64 targets and this will be moot. Linux is already on track to be exclusively 64-bit in a few years.
Perhaps there's a command line switch to select x64 when performing the meson setup?
Copying the Win32 configuration into an x64 configuration with the VS configuration manager leads to some link-time errors related to the .obj files being incompatible with the target. I have not determined if this is a basic problem with the toolset or PEBKAC. I am a meson newb and I twiddled the x64 configuration in the usual MSBuild manner.
On the whole, meson did make it pretty easy.

The Win32 configuration created by meson builds perfectly, 21 projects of 21 selected.
Doing a git pull and building works correctly and the local repo is tracking correctly with Skuller's changes.
If all you want is a Win32 x86 setup, this is very practical.
The toolset magically pulls in all the subprojects but they are untracked within git. This is reasonable and not unexpected.
It also ignores the vcpkg libraries I already installed that should have satisfied those linkages. I would have been happier if it used the vcpkg libraries rather than pulling in those subproject sources. I have not investigated this further.
There is a meson tool within vcpkg. Perhaps this tool would recognize the correct dependencies and refer to the packages vs pulling in all new sources. This will make it much more Linux-like. Part of me is very tired of crawling the Internet looking for programs to install from various sources for one reason or another. Vcpkg solves a lot of these issues. I have a powershell script that updates and maintains all my installed packages so I am always up to date.

The resulting meson-built project view in the VS IDE sucks. An example: the `q2pro` project lists four main.c files:
src\client\sound\main.c
src\refresh\main.c
src\client\main.c
src\server\main.c
One has to be VERY careful to be sure you are opening the correct one. The IDE might save you from having to worry about it if you're relying on it to cross-reference objects and it might take you to the appropriate references as you edit, but I'd still be cautious for a time. I expect the debugger will be 100% correct about taking you into the correct file on a stack frame trace.

The problem with the Cmake and meson tools is that if you are doing cross-platform and using VSxxxx along side WSL or another Linux VM is that you have to keep two independent repositories of the same project. This makes editing sources to accomodate portable code a real mess. Reconfiguring them in a common repository breaks one or the other, especially CMake projects. One cannot keep independent targetting toolsets within a common source repo in CMake. With a pure MSBuild solution and a Makefile, this is a non-issue.

**Comment by skullernet** [comment]
> Perhaps there's a command line switch to select x64 when performing the meson setup?

It depends on whether Meson finds x86 or x64 toolchain in PATH. If running Meson from "x64 Native Tools Command Prompt" it should find x64 toolchain.

> It also ignores the vcpkg libraries I already installed that should have satisfied those linkages. I would have been happier if it used the vcpkg libraries rather than pulling in those subproject sources. I have not investigated this further.

I'm not familiar with vcpkg, but Meson looks for libraries via pkg-config first and if not found falls back to bundled wraps. If vcpkg provides *.pc files, pkg-config is installed and PKG_CONFIG_PATH environment variable points to the right directory it should find them.

> An example: the q2pro project lists four main.c files

Yes this sucks, if Visual Studio can't be configured to show relative paths.

> Reconfiguring them in a common repository breaks one or the other, especially CMake projects. One cannot keep independent targetting toolsets within a common source repo in CMake.

Not sure what you mean. Both CMake and Meson support out of tree builds that are completely independent of source directory.
