### ISSUE TITLE
cl_weaponmodel irregularity

### ISSUE THREAD

**Issue by MVarland** [skullernet/q2pro#293]
- Q2PRO version: This has been in q2pro for at least 6 months.
- OS version
A: Windows 10 64Bit
B: Windows 11 64Bit, but I think this issue was there for me in Windows 10 also

- GPU driver and version
A: NVIDIA 531.29
B: NVIDIA 531.29

### Reproduction steps

draw cl_weaponmodel 0 -1
cl_gun 1
hand 2

Switch weapon whilst using the settings above and watch for changes in cl_weaponmodel

### Expected behavior

It would be great if we could have Player A's behaviour for everyone for to scripting purposes like
trigger "if sniper isin $cl_weaponmodel then msg[leg]" "*You hit * in the legs*"

### Actual behavior

Player A
$cl_weaponmodel is populated irrespective of cl_gun and hand settings

Player B
$cl_weaponmodel is only populated if cl_gun = 1 and hand != 2.

Also if player B changes settings so that $cl_weaponmodel is populated, and then sets hand 2 or cl_gun 0:
The value of $cl_weaponmodel sticks and does not change whilst switching weapons.

**Comment by skullernet** [comment]
If the gun is invisible due to `cl_gun` and `hand` settings, `cl_weaponmodel` is undefined when using R1Q2 or Q2PRO network protocols because server stops sending gun updates. Q2PRO supports additional hack that if `cl_gun` is set to -1, gun will be invisible, but server will still send gun index updates so that `cl_weaponmodel` should work.
