### ISSUE TITLE
OpenAL issues

### ISSUE THREAD

**Issue by Paril** [skullernet/q2pro#327]
I've been testing the OpenAL driver a bit for reverb support, and I suspect that something might be wrong configuration-wise - I haven't had the time to experiment yet, but if possible, can you (or anybody coming across this issue) confirm this? I'm using the latest OpenAL-Soft release, not the Creative driver.

* In newer OpenAL-Soft, HRTF defaults to enabled and is used on all samples - including music. This causes the music especially to sound very muddy; see https://github.com/kcat/openal-soft/issues/211 https://github.com/kcat/openal-soft/issues/357 for info about this particular issue and what we can do to avoid it.
* music sounds very different than DMA (with HRTF forcefully not enabled, of course; I made sure that `ALC_HRTF_STATUS_SOFT` was reporting 0); see this video for a sample: https://streamable.com/hxhkz8 it sounds like it's being mixed monaurally (the drums on the right are in the center). My headphones are set to 2 channel, so it's not some weird issue with 7 or 8 faux-channel headphone setting.
* attenuation seems to be ever-so-slightly incorrect in AL. In the re-release, please check `map test/paril_soundstage` which is a map I wrote to test our attenuation with XAudio vs vanilla Q2. Stepping on a teleporter will play a sequence of sounds at diminishing distances at each main attenuation level, and notes when the sound should be completely inaudible (volume == 0 on the software mixer). It seems like AL is diminishing ever-so-slightly too fast.

**Comment by skullernet** [comment]
> In newer OpenAL-Soft, HRTF defaults to enabled and is used on all samples - including music.

I'll look into HRTF issue, seems not a hard thing to fix.

> music sounds very different than DMA

DMA and OpenAL sounding differently is somewhat expected, considering how low quality DMA resampler is. You should really only consider doing comparison when output sample rate (set by `s_khz`) matches source (48 kHz for music). Whether it's stereo or monaural you can test it with this [sample](https://github.com/skullernet/q2pro/files/13183437/test.zip) (.zip because github doesn't allow .ogg, huh).

> attenuation seems to be ever-so-slightly incorrect in AL

Hmm, I checked out your test map and honestly I don't hear any difference between DMA and OpenAL regarding sound attenuation. All attenuation levels that should be audible are audible with both, and those that should not are inaudible. I had to disable the chat beep though because it prevents from hearing the sound at low volume.

That said, I only did my testing with OpenAL 1.19.1 which is default on my system. I'll try to compile the latest version and re-test.

**Comment by Paril** [comment]
Thanks re HRTF.

I didn't consider the resample quality for DMA, good point, but my main issue was that the spatialization of the music sounds entirely wrong, not necessarily the quality (although the DMA one does sound crisper still for some reason). I tried forcing AL to 48000 as well but that seemed to make no difference.

I think you're right regarding the sound stage, it must be the message beep that was hiding it for me. I re-tested it again at s_volume 1 and I can hear it where I couldn't before when the message relayed 7 volume, so this one might be a non-issue.

**Comment by skullernet** [comment]
I've added code to disable HRTF by default and additionally make raw samples bypass HRTF in case it is enabled. Tested with OpenAL Soft 1.23.1 and it seems to work as expected. Closing.
