### ISSUE TITLE
How to deal w/ HTTP download servers returning 404s?...

### ISSUE THREAD

**Issue by res2k** [skullernet/q2pro#349]
So I recently came across a server that reported a HTTP download URL.
However, the reported URL was technically working, but empty - so all download attempts failed with a 404.
The workaround was to manually disable HTTP downloads, as UDP downloads are fine.

Now, I can see that 404s are handled specially, essentially failing a download without the UDP fallback kicking in.
However, in my case, falling back to UDP would actually have been the desirable action.

So, I wonder, maybe it would make sense to fall back to UDP even if HTTP reported a 404?
But I'd also like to understand why the current behavior was chosen - so could you explain the reasoning (or point to an explanation)?

**Comment by skullernet** [comment]
Current behavior was chosen due to speed concerns. HTTP downloads are fast, but falling back to UDP is slow. To ensure all clients enter the server as fast as possible, 404 from HTTP server is considered definitive and failed downloads are not retried.

In general, server admins are required to keep HTTP download servers up to date. Broken configurations where some files are available only over UDP and not HTTP are not really supported.

Also consider the case when someone runs e.g. [pakserve](https://github.com/skullernet/pakserve) to serve HTTP downloads from game data. If UDP fallback is attempted, then for each missing file there will be two failing requests, one HTTP and one UDP, which is very redundant.
